### ISSUE TITLE
Macbook Pro questions about preparing to use a GPU for deep learning

### ISSUE THREAD

**Issue by mattwarkentin** [rickeycarter/macDeepLearning#2]
Hi Rickey,

Thank you for preparing and sharing all these documents. They are as helpful as they are relevant/needed in the community. For context, I am Macbook Pro user currently running Mojave 10.14.4. I have two questions I am hoping you can help answer:

1) If I am planning to use my Macbook and the terminal only to SSH into a high-performance computing cluster running a Linux OS with a NVIDIA GeForce GTX 1080 Ti, do I need to follow this procedure? Or is this procedure only for those wanting to directly connect/run a NVIDIA eGPU with their Macbook?

2) If I do need to do all this work to prepare my Macbook, is this repo still the guidance I should follow? I see it hasn't been updated in many months, and I just want to ensure this information is still the correct approach before I start this whole process.

Thank you for your time.

**Comment by rickeycarter** [comment]
If you are connecting to a fully configured remote server with the necessary libraries, you should be set with no modification to your current MacOS.  The configuration instructions are only applicable to having the Mac itself be the deep learning "server". 

Mojave presents a new set of challenges for NVIDIA drivers (in that it may not work at all). I have hope that with the new Mac Pro that is being released that NVIDIA and Apple with mend their past and the mac pro could be a high end deep learning workstation.

**Comment by mattwarkentin** [comment]
@rickeycarter Thanks for the response. I can only speculate (but I will investigate), but since this HPC is managed by my research institute with the specific goal of enabling GPU-based deep learning, I think it should be fully configured. 

Assuming proper configuration, I should be able to write a R script using tensorflow-gpu and then submit the job to the HPC's GPU node. The OS on my Macbook Pro would be irrelevant in this scenario, correct? So long as the cluster/GPU is properly configured.

I agree, I hope Apple and NVIDIA can make this work more seamlessly moving forward.
